import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// cursors.css — the bamboo-slip theme's mouse cursors.
//
// The file is generated by scripts/gen_cursors.py, and every way a cursor can be
// wrong FAILS SILENTLY: a data URI the browser cannot parse, a hotspot outside
// the image, and a missing keyword fallback all just leave the system cursor in
// place. Nothing reaches the console. So the invariants are pinned here — this
// is the only place a mistake in them shows up before a user notices that the
// theme "did nothing".

const here = dirname(fileURLToPath(import.meta.url));
const css = readFileSync(join(here, '../cursors.css'), 'utf8');
const indexHtml = readFileSync(join(here, '../../index.html'), 'utf8');

const SET = 'bamboo';
const SEL = `:root[data-theme="bamboo-ancient"][data-cursor="${SET}"]`;

/** Every `cursor:` declaration, keyed by the kind it overrides. */
const rules = Object.fromEntries([...css.matchAll(
    /cursor:\s*url\("data:image\/svg\+xml,([^"]+)"\)\s*(\d+)\s+(\d+),\s*(default|pointer|text);/g,
)].map(([, uri, hx, hy, kind]) => [kind, {
    svg: decodeURIComponent(uri), hx: +hx, hy: +hy,
}]));

const all = Object.values(rules);
const size = (svg) => ({
    w: +svg.match(/width="(\d+)"/)[1],
    h: +svg.match(/height="(\d+)"/)[1],
});

describe('cursors.css', () => {
    it('covers default, pointer and text, and nothing else', () => {
        expect(Object.keys(rules).sort()).toEqual(['default', 'pointer', 'text']);
        expect(css).toContain(SEL);
        // Three distinct drawings, not one pasted three times.
        expect(new Set(all.map((r) => r.svg)).size).toBe(3);
    });

    it('is reachable from index.html', () => {
        // The stylesheet does nothing on its own: the rules need data-cursor on
        // <html>, and the boot script is the only thing that sets it. Linking one
        // without the other is silent — hence both halves are checked together.
        expect(indexHtml).toContain('styles/cursors.css');
        expect(indexHtml).toContain(`'${SET}'`);
        expect(indexHtml).toContain('dataset.cursor');
    });

    it('rejects a data-cursor value the stylesheet does not define', () => {
        // The set was renamed once during review. A stale localStorage value
        // would otherwise set an attribute matching no rule, and the theme would
        // quietly fall back to system cursors with nothing to explain why.
        const list = indexHtml.match(/var SETS = \[([^\]]*)\]/);
        expect(list).not.toBeNull();
        const names = list[1].split(',').map((s) => s.trim().replace(/'/g, ''));
        // Every non-empty name must actually exist in the stylesheet. '' is the
        // one legitimate way to ask for the system cursors.
        for (const name of names.filter(Boolean)) {
            expect(css).toContain(`[data-cursor="${name}"]`);
        }
        expect(names).toContain('');
    });

    it('scopes every rule to the bamboo theme, so no other theme is touched', () => {
        // A bare [data-cursor=…] would put the brush on the light theme too.
        const selectors = css.match(/^[^@/*\s][^{]*[,{]$/gm) || [];
        expect(selectors).not.toHaveLength(0);
        for (const sel of selectors) {
            expect(sel).toContain('[data-theme="bamboo-ancient"]');
        }
    });

    it('encodes the characters that break a data URI', () => {
        // `#` is the fatal one — unencoded it starts a fragment and truncates the
        // SVG mid-colour. `<`/`>` are tolerated by Chromium but not everywhere.
        const uris = css.match(/data:image\/svg\+xml,[^"]+/g) || [];
        expect(uris).toHaveLength(3);
        for (const uri of uris) expect(uri).not.toMatch(/[#<>]/);
    });

    it('round-trips every URI back into a parseable SVG', () => {
        for (const { svg } of all) {
            expect(svg.startsWith('<svg')).toBe(true);
            expect(svg.endsWith('</svg>')).toBe(true);
            expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"');
        }
    });

    it('keeps every hotspot inside its image', () => {
        // Chromium DISCARDS a cursor whose hotspot falls outside the bitmap and
        // silently uses the default — the exact failure this file exists to avoid.
        for (const { svg, hx, hy } of all) {
            const { w, h } = size(svg);
            expect(hx).toBeLessThan(w);
            expect(hy).toBeLessThan(h);
        }
    });

    it('keeps every glyph within the size a cursor can actually be', () => {
        // Cursor bitmaps do not scale with the display, and Windows discards
        // anything above 32x32.
        for (const { svg } of all) {
            const { w, h } = size(svg);
            expect(w).toBeLessThanOrEqual(32);
            expect(h).toBeLessThanOrEqual(32);
        }
    });

    it('keeps every shape inside its own canvas', () => {
        // A shape running off the edge is clipped without complaint, and the
        // clipped part is usually the widest — the mass that makes the silhouette
        // read. Strokes add ~0.6, so the usable range is inset by that.
        for (const { svg } of all) {
            const { w, h } = size(svg);
            const pts = [...svg.matchAll(/[ML] ?(-?[\d.]+) (-?[\d.]+)/g)]
                .map((m) => [+m[1], +m[2]]);
            expect(pts.length).toBeGreaterThan(0);
            for (const [x, y] of pts) {
                expect(x).toBeGreaterThanOrEqual(0.6);
                expect(x).toBeLessThanOrEqual(w - 0.6);
                expect(y).toBeGreaterThanOrEqual(0.6);
                expect(y).toBeLessThanOrEqual(h - 0.6);
            }
        }
    });

    // ── what two rounds of review changed ───────────────────────────────────
    // Both findings were about legibility, not taste. These say what "fixed"
    // means so a later tweak cannot quietly walk back into either one.

    it('never fills a glyph with ink', () => {
        // --bg-primary is #3a2e1e. The first brush tuft was solid #1a1208 and
        // could not be found on the page — the POINTING END was the least visible
        // part of the pointer. Ink is an outline colour here and nothing else.
        for (const { svg } of all) expect(svg).not.toMatch(/fill="#1a1208"/i);
    });

    it('fills the pointing tip of each glyph pale', () => {
        // The paper fill is what makes a tip findable on charred bamboo.
        expect(rules.default.svg).toContain('fill="#f2ead6"');
        expect(rules.pointer.svg).toContain('fill="#f2ead6"');
        expect(rules.text.svg).toMatch(/fill="#(d9c9a3|f2ead6)"/i);
    });

    it('keeps the pointer’s upright wide enough to read as a finger', () => {
        // The second finding: at 5.4px the protruding slip read as a splinter,
        // and against a 20.2px bundle the ratio was 0.25 where the OS hand is
        // ~0.37. Widening the slip and narrowing the bundle brought it to 0.36.
        // Both numbers are literals in the drawing, so they can be checked here;
        // the RENDERED ratio needs getBBox, which jsdom lacks, and is verified in
        // a browser instead.
        const slip = rules.pointer.svg.match(/<rect x="5\.5" y="2" width="([\d.]+)"/)
            || rules.pointer.svg.match(/<rect x="5\.5" y="2\.0" width="([\d.]+)"/);
        expect(slip).not.toBeNull();
        const bundle = rules.pointer.svg.match(/<rect x="2\.4" y="13\.4" width="([\d.]+)"/);
        expect(bundle).not.toBeNull();
        expect(+slip[1] / +bundle[1]).toBeGreaterThanOrEqual(0.33);
    });

    it('puts the hotspot on the tip that does the pointing', () => {
        // The arrow points up-left along the diagonal, so its tip is the corner.
        expect([rules.default.hx, rules.default.hy]).toEqual([2, 2]);
        // The protruding slip stands upright on x=9, like a hand's fingertip.
        expect([rules.pointer.hx, rules.pointer.hy]).toEqual([9, 2]);
        // The slat is a bar; its hotspot is its middle.
        expect(rules.text.hy).toBe(15);
    });

    it('reserves verdigris for the interactive cursor', () => {
        // The accent means "you can click this". If the arrow carried it too, it
        // would stop meaning anything.
        expect(rules.pointer.svg).toContain('#7fc4b8');
        expect(rules.default.svg).not.toContain('#7fc4b8');
        expect(rules.text.svg).not.toContain('#7fc4b8');
    });
});
